name: Run Testsuite

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [master]

jobs:
  run-phpunit:
    name: Run php-unit
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        composer install --ignore-platform-reqs -v

    - name: Run Testsuite
      run: |
        vendor/bin/phpunit --testdox
